export default {
  nav:{
    inicio: 'Home',
    in:'LinkedIn',
    web: 'Web',
    redes: 'Media & Ads',
    com: 'Communication',
    contacto:'Contact'
  },
  footer:{
    services:{title:'Services', p:{p1:'Web Design & Development',p2:'Social media & Ads', p3:'Communication'}},
    others:{title:'More', p:{p1:'Contact', p2:'Work with us'}}
  },
  socialMedia:{
    ig:'oddelmarketing',
    in:'oddelmarketing',
    fb:'oddelmarketing'
  },
  title:'Increase your online revenue with the aid of Oddel Marketing',
  sub: 'Our services include website development, social media optimization and online advertisement that in return can help grow your brand',
  sub2: 'Tell us about your brand and get a free consultation',
  form1:{
    title:`Let's talk digital marketing`,
    nombre:'My name is',
    mensaje:'My enquiry',
    mail:'My email',
    button:'Contact'
  },
  wwh:{
    title1:'Why Marketing?',
    p1:'Digital marketing is a vital tool in today’s organizations. It has changed the business world; the way companies make themselves known and the way they communicate.',
    alt1:'Megaphone',
    title2:'How do we work?',
    p2:'We have an expert team in every needed area to provide a service that is original, complete, and adaptable to each client´s profile.',
    alt2:'Hands shaking',
    title3:'Who are we?',
    p3:'Oddel Marketing is a professional marketing and digital communication organization with massive focus on serving our customers. We design and create websites, branding and advertising strategies for you no matter how big or small!',
    alt3: 'Goup of people'
  },
  services:{
    title:'We are experts at',
    title1:'Web design & development',
    p1:'We offer an integral service for your landing page, general website for services, e-commerce website, or web app',
    title2:'Social media, SEM and SEO',
    p2:'The goal of online marketing is to raise awareness and visibility. We can help businesses build brand awareness and create a positive online presence for your organization',
    title3:'Visual communication',
    p3:'We can help your brand stand out from the crowd! Look at our communication services and start making a statement with your clients',
    title4:'LinkedIn',
    p4:'Contacta con los profesionales y las empresas que buscas. Te ofrecemos un servicio profesional de administración de LinkedIn apuntado a conseguir tus objetivos'
  },
  buttons:{
    see:'See more',
    pres:'Request quote',
    counseling:'Get free audit'
  },
  internarional:{
    title:'We are international',
    p:'Oddel marketing has clients across the world, we can translate web pages for clients in order to help smaller brands access international markets. We also work with clients in various languages.',
    alt:'Map of the world',
    mapCode:'01',
  },
  clients:{
    title:'Our clients',
    p:'We are backed up by a national and international client portfolio, and we keep paving roads to help new partners break through the digital environment.'
  },
  counseling:{
    title:'We can help you achieve your goals',
    p:'Contact us for an initial analysis where we will look at your marketing strategy and see how we can grow your organisation (Free of charge of course).',
  },
  web:{
    title:'Web design and development',
    sub:'We create unique website projects in order to increase the usability, conversion and traffic of your website.',
    button:'Get website quote',
    title1:'Custom website',
    p1:'Gone are the days of having to spend thousands of euros on creating a functional website. Almost seven in ten (69%) internet users purchased goods and/or services online in 2020. Oddel can create a unique website to your liking, where the (SEO friendly) set up and branding alone will drive potential customers to your website. This is vital given the previous events we have all experienced in the last year, it can be seen that organisations without a good website would have sunk, with those who had a competent website swam.',
    button1:'Enquire about a website',
    bullet11:'Website can enable effortless international trade and access to bigger markets',
    bullet12:'Websites allows you to trade with little boundaries',
    bullet13:'Advertising online is low-cost',
    title2:'E-commerce',
    p2:'An ecommerce website is an effective way forward for you if you want to boost sales easier, lower operating expenses, and enhance profit margins. An E-commerce store is open 24/7 and allows you to use a variety of marketing and sales strategies to entice visitors to stay on your site and buy your products.',
    button2:'Enquire about getting started',
    bullet21:'Reduced starting and operational costs',
    bullet22:'Can be operated remotely and elements automated',
    bullet23:'Easier to scale',
    title3:'Landing page',
    p3:'A Landing Page is the next step in online consumers journey after searching online and actually converting into a real customer. It is a stand alone page different from your homepage, but equally as important. A landing page is an excellent approach to increase visitors, boost SEO, and establish your brand. It can also be used as part of a successful PPC campaign.',
    button3:'Enquire about a Landing Page',
    bullet31:'They generate leads and conversions',
    bullet32:'They promote new products and services',
    bullet33:'They build credibility',
  },
  media:{
    title:'Social media & SEO',
    sub:'Make your brand reach your potential clients easily. With our social media and ads service you will get straight to your target audience.',
    button:'Get quote',
    title1:'Social Advertisement',
    p1:'People spend most of their time on social media and it is a major area for your company to take advantage of. Social media is one of the most effective and less expensive ways to advertise online. Facebook Ads for example allows an extensive and in depth segmentation of your market and gives you total control of your ads, allowing access to over 2.80 billion monthly users. Facebook also directly integrates with Instagram allowing content to easily be created for both platforms.',
    button1:`Let's talk Social`,
    title2:'Google ADS',
    p2:`Google Search advertising can provide an incredibly valuable feature of ensuring that your advertisement is viewed. However, there's no assurance that consumers will click it or even read it—a lot depends on the ad's quality. When you do acquire a spot on Google's main page, you can quickly start tracking the gains you've made owing to paid ads.`,
    button2:`Let's get started on Google`,
    title3:'SEO and SEM',
    p3:'Search Engine Optimization (SEO) and Search Engine Marketing (SEM) will allow people to reach your website organically. A good digital marketing strategy that mixes SEO and SEM will allow your brand to be constantly positioned in the Google searches getting more views and better results.',
    button3:'Lets grow organically',
    title4:'Content creation, design and programming uploads on your social media',
    p4:'Nowadays brands communicate frequently with their audience, mostly through social media. Using different types of media allows you to touch base daily with your clients. This is why it is really important for companies to have proper and professional profiles on social platforms for their target clients to see. Participating, giving opinions, sharing and recommending are some examples of activities that people love doing on social media. By doing these small things, your company can increase the loyalty and engagement of your customers.Quality and engaging content, plus good profile management on your social media are key to reach a better audience and increase the right type of followers on social channels. Oddel´s team can develop this content and manage it for achieving a solid customer base that become fans of your company, and hence sales soar in your business.',
    button4:`Let's grow my media`,
  },
  com:{
    title:'Visual communication',
    sub:'We craft unique pieces that turn your website’s traffic into potential customers',
    button:'Get design packs quote',
    title1:'Logo',
    p1:`Your company's logo is your statement to the world. It puts your stamp on your brand and what you stand for. It is crucial to give it the importance it deserves, not only to create it but to modify and update it as well, making it attractive and friendly to the user.<br>The audience changes through time and your logo should keep up. Oddel’s professional team together with your ideas and expectations will study your target and those influencing factors to determine which will be the best design for your logo.`,
    button1:'Get my logo',
    title2:'Merchandising',
    p2:`Something as simple as how your products look online is how you will stand out from competitors. Selling and promoting are a key aspect of any marketing strategy, but how your products look is also extremely important to consider. These actions attract clients to your brand and make them closer to it and result in higher conversions. In Oddel we can take charge of the necessary elements to make your Merchandising strategy optimal and capture the market's attention by adapting to whatever industry you are in.`,
    button2:'Enquire about merchandising',
    title3:'Video animation and photo',
    p3:'There are several ways to be disruptive in the digital world, and one of them is to make high impact content with strong messages. This can be done through videos and images. Help your business grow, communicate its values, products, and ways of working with audiovisual elements that will attract the audience, generate interaction, and empower your brand.',
    button3:'Enquire about Video and Photo',
  },
  in:{
    title:'LinkedIn',
    sub:'Linkedin eases networking with strategic partners while providing you valuable competitor´s and market information. Know how your business can grow with this social media.',
    button:'I want to grow with LinkedIn',
    sabias: 'Did you know that LinkedIn has a global user base of over <b>774 million</b> people?',
    alt1: 'A representation of the world with icons of business people all arround',
    ademas: 'Futhermore, <b>4 out of every 5</b> LinkedIn users in a position to <b>influence crucial business decisions</b>',
    ademas_2: `That makes LinkedIn one of the most effective ways to get your services and products in front of the right people`,
    sabemos: 'Grow Your Business with LinkedIn Marketing',
    sabemos_2: 'Being one of the only companies in the market offering this service, Oddel can help you achieve your goals and grow your business on LinkedIn, putting your product/service in front of the right decision makers',
    bullets:{
      t1:'Build Awareness',
      p1:`Attract the attention of the world's most influential decision-makers`,
      t2:'Drive Website Traffic',
      p2:'Send potential customers right to the source for more information about your products and services',
      t3:'Generate Leads',
      p3:'Use remarketing and direct connections, in order to get the right content and information across which will convert into leads'
    },
    optimation:{
      title:'How do we optimize your profile?',
      list_titles:['Profile creation', 'Institutional video','Professional bio',
                  'Instititional banner', 'Part-time specialist', 'Content creation and upload',
                  'Monthly content presentations', 'Potential customers identifying',
                  'Contact and follow-up with clients', 'Interactions and connections request management'
                  ]
    }
  },
  contact:{
    title:'Contact us',
    p1:'We can provide your business with every tool you need to position it.',
    p2:'We would like to be part of your team and work together. Our intention is to go beyond the work links and implement a partner-friend vision, interiorizing in your company to provide a better service.',
    p3:'We will dedicate to your concerns and goals, working hard to achieve magnificent results together.',
    faqTitle:'FAQs',
    f1:'Digital marketing is the implementation of marketing strategies carried out in digital platforms.',
    f2:'Digital marketing is used to contact the seller of a product or service with its potential customers through digital platforms. Its benefits are: global reach, measurable results and immediacy.',
    f3:'A conversion process consists in attracting users to our website, created to offer the right content according to its buying cycle.',
    f4:'A bid is an auction in which our campaign will participate with other advertisers. Those who pay more will be those who appear first.',
    f5:'Online Marketing and Digital Marketing are not the same, since online marketing is based only on the use of the internet, while digital marketing covers all digital media.',
    f6:'A cookie is a piece of information in the user´s browser.  It is used to record user activity on a site and track, for example, the number of times the user has visited the website.',
    f7:'The Engagement is the “commitment” that the users have with a brand due to the products ability to create a solid and lasting relationship with them. These are not all brand followers, but those who interact with it.',
    f8:'Affiliate marketing consists in making a series of agreements with other websites to promote your content in exchange for a commission. Each time that someone clicks on the banner that you have in another website it will take a previously agreed commission. The same happens the other way around for those who want to advertise on your website. If there is agreement, then there is affiliation.',
    f9:'Remarketing is a marketing technique that consists on showing your ads to people who have seen a specific page on your website.',
    f10:'Nowadays, Traditional Marketing has many limitations in terms of target segmentation, in addition to its great difficulty in measuring impact and its ROI, instead, digital marketing focuses its strategy on target audience segmentation (age, gender, interests, city, country, purchasing power, mood, data of interest, among many more).',
    f1t:'What is digital marketing?',
    f2t:'What is Digital Marketing for?',
    f3t:'Which are the metrics used in digital marketing?',
    f4t:'What is a bid?',
    f5t:'Is Online Marketing the same as Digital Marketing?',
    f6t:'What is a cookie?',
    f7t:'What is Engagement?',
    f8t:'What is affiliate marketing?',
    f9t:'What is Remarketing?',
    f10t:'What is the Difference Between Digital Marketing and Traditional Marketing?',
  },
  links:{
    home:'/index',
    in: '/linkedin',
    web:'/web',
    media:'/media-ads',
    com:'/communication',
    contact:'/contact',
  },
  form2:{
    l1:'My name is',
    l2:`I would like information about`,
    l3:'Message:',
    l4:'Contact email',
    small:'All our services include a free consultation',
    button:'Contact me',
  },
  endForm:{title:'Ready to innovate your business?', p:`Tell us about your business and we'll give you a free audit`}
}
