export default{
  nav:{
    inicio:'Inicio',
    in:'LinkedIn',
    web:'Web',
    redes:'Redes y ads',
    com:'Comunicación',
    contacto:'Contacto'
  },
  footer:{
    services:{title:'Servicios', p:{p1:'Diseño y desarrollo web',p2:'Social media y Ads', p3:'Comunicación visual'}},
    others:{title:'Otros', p:{p1:'Contacto'}}
  },
  socialMedia:{
    ig:'oddelmarketing',
    in:'oddelmarketing',
    fb:'oddelmarketing'
  },
  title:'Haz crecer tus ventas con una buena estrategia',
  sub: 'Te ofrecemos un servicio integral en web, social media, ads y posicionamiento para que tu marca despegue',
  sub2: 'Contanos sobre tu marca y accede a una asesoría gratis',
  form1:{
    title:'Queremos escucharte',
    nombre:'Mi nombre es',
    mensaje:'Mi mensaje',
    mail:'Mi mail es',
    button:'contactarme'
  },
  wwh:{
    title1:'¿Por qué marketing?',
    p1:'El marketing digital es una herramienta vital en las organizaciones actuales. Revolucionó el mundo de los negocios, la forma en que las compañías se dan a conocer y la manera de comunicarse.',
    alt1:'Megáfono',
    title2:'¿Cómo trabajamos?',
    p2:'Contamos con un grupo de expertos en cada área necesaria para brindar al público un servicio completo, original y adaptable al perfil de cada cliente.',
    alt2:'Apretón de manos',
    title3:'¿Quiénes somos?',
    p3:'Somos una empresa de marketing y comunicación digital profesional, con gran foco en el compromiso. Creamos estrategias de branding y publicidad para que tu compañía o emprendimiento crezcan exponencialmente.',
    alt3:'Grupo de personas'
  },
  services:{
    title:'Somos expertos en',
    title1:'Diseño web y desarrollo',
    p1:'¿Conocés la importancia de tener tu propia web? Te ofrecemos un servicio integral para tu landing page, e-commerce, o aplicación web',
    title2:'Social media, SEM y SEO',
    p2:'¿Sabías que con unas pocas estrategias tu negocio puede crecer a gran escala? Con nuestro servicio de redes y Ads vas a llegar a tu público como nunca.',
    title3:'Comunicación visual',
    p3:'¿Queres que tu marca se destaque? Conocé nuestros servicios de comunicación y comenzó a generar una experiencia memorable con tus consumidores',
    title4:'LinkedIn',
    p4:'Contacta con los profesionales y las empresas que buscas. Te ofrecemos un servicio profesional de administración de LinkedIn apuntado a conseguir tus objetivos',
    endTitle:'¿Listo para innovar con tu web?',
    endP:'Cuéntanos sobre tu negocio para que podamos asesorarte sin costo',
  },
  buttons:{
    see:'Ver más',
    pres:'Solicitar presupuesto',
    counseling:'Quiero asesorarme'
  },
  internarional:{
    title:'Somos internacionales',
    p:'Trabajamos en distintas partes del mundo. Contamos con servicio de traducción para que tu marca pueda crecer globalmente',
    alt:'Mapa del mundo',
    mapCode:'02',
  },
  clients:{
    title:'Nuestros clientes',
    p:'Nos avala una cartera de clientes nacionales e internacionales, y continuamos abriendo caminos para sumar nuevos socios que se encuentren dispuestos a romper los paradigmas digitales'
  },
  counseling:{
    title:'Te asesoramos sin costo',
    p:'Contactate con nosotros para que analicemos tu estrategia de marketing y te asesoremos de manera gratuita',
  },
  web:{
    title:'Diseño y desarrollo web',
    sub:'Creamos experiencias únicas para convertir el tráfico de tu web en potenciales clientes',
    button:'Presupuestar mi web',
    title1:'Web Personalizada',
    p1:'Ya no es necesario ir a buscar a los clientes, ellos pueden ser atraídos a tu marca.<br> Una Web Site es clave para mejorar la posición en los motores de búsqueda, con lo que aparecerás adelante en las búsquedas de Google, también da credibilidad y respaldo a tu marca, creando una interacción con los posibles compradores donde pueden hablar contigo, solicitando producto o servicios',
    button1:'Quiero una web',
    bullet11:'Alcance sin límites',
    bullet12:'Publicidad y campañas a bajo costo',
    bullet13:'Llegada a nuevos clientes, hasta niveles internacionales',
    title2:'Landing page',
    p2:'Una Landing Page puede ser un gran aliado para atraer visitas a tu página y ventas. Si esta, se encuentra correctamente conformada, y tiene un aspecto visual llamativo, probablemente generará que el público se involucre con tu marca.<br>Esta página será el primera pantallazo de los posibles clientes con nuestra marca, y su buena composición finalizará en suscripciones, consultas o ventas a favor de tu marca.',
    button2:'Quiero una Landing Page',
    bullet21:'Accesibilidad y velocidad de carga',
    bullet22:'Eficacia, focalizándose en datos útiles para nuevos interesados',
    bullet23:'Conversión de visitantes a clientes',
    title3:'E-commerce',
    p3:'Comprar o vender durante todo el día, algo que solo era posible sin descanso e incurriendo en enormes gastos, ahora es una posibilidad palpable a través de Internet. E-commerce, tu negocio estará abierto las 24 horas, dirigiéndose a un público específico con una comunicación que lo capte rápidamente, y pudiendo crear campañas de comunicación a bajo costo especializadas.',
    button3:'Quiero un e-commerce',
  },
  media:{
    title:'Social media y SEO',
    sub:'Haz que tu marca llegue a los potenciales consumidores de manera ágil y orgánica',
    button:'Quiero un presupuesto',
    title1:'Facebook Ads',
    p1:'Las personas pasan gran parte de su día dentro de redes sociales, y tu empresa debe aprovecharlo. Las redes son uno de los medios más efectivos y menos costosos de comunicación.<br>Facebook Ads, permite una segmentación exhaustiva de tu mercado y brinda un control total de tus anuncios. De este modo, se puede accionar a partir de objetivos claros y detallados.<br>Es importante contar con profesionales que entiendan esta plataforma y estén familiarizados. Así, con un trabajo en conjunto rápidamente se verá mayor participación en el mercado y más interacción con el público.',
    button1:'Quiero anunciar en redes',
    title2:'Google Ads',
    p2:'Google es el dueño del 95% de las búsquedas en la web. Su herramienta, Google Ads, te ayuda a incrementar tus ventas haciendo que más gente ingrese a tu sitio web. Esto aumenta los clientes potenciales y el conocimiento de tu marca en el mapa mental de los consumidores.<br>Google Ads es un método publicitario que tienen como fin aumentar la conexión con tus clientes y brinda, a su vez, múltiples herramientas para que puedas observar el rendimiento de tus anuncios para mantenerte al tanto de los cambios día a día',
    button2:'Quiero anunciar en Google',
    title3:'SEO y SEM',
    p3:'Este conjunto hará que las personas lleguen a tu página, que tengas más presencia en los motores de búsqueda y que tengas el potencial de realizar un mayor número de ventas.<br>Una buena estrategia de marketing digital que mezcle SEO y SEM permitirá que tu marca se posicione constantemente en las búsquedas de Google, obteniendo más visitas y mejores resultados.',
    button3:'Quiero aparecer en buscadores',
    title4:'Creación, diseño y candelarización de contenidos para tus Redes sociales',
    p4:'Las marcas hoy comunican todo el tiempo y lo hacen a través de sus redes sociales. Este medio, permite una interacción diaria con tus clientes. Es necesario que las empresas tengan desarrollados perfiles en las redes sociales que su target utilizan.<br>Participar, opinar, compartir y recomendar, son algunas de las actividades que las personas aman hacer en las redes sociales. Y si las misma se pueden realizar con tu marca, la fidelización de estos clientes será para siempre<br>La creación de contenido exclusivo y de calidad, y un correcto manejo de los perfiles en las redes sociales, es fundamental para obtener mayor cantidad de seguidores. El equipo de Oddel puede crear ese contenido y administarlo, de modo que tus fans aumenten exponencialmente, y junto con ellos, tus ventas',
    button4:'Quiero que mis redes crezcan',
  },
  com:{
    title:'Comunicación visual',
    sub:'Creamos experiencias únicas para convertir el tráfico de tu web en potenciales clientes',
    button:'Presupuestar diseño',
    title1:'Logo',
    p1:'La imagen de tu empresa ante el mundo es tu logo. Es su sello, la representación de la marca. Es crucial darle la importancia que merece, no solo al diseñarlo en su creación sino a modificarlo y actualizarlo a través del tiempo, haciéndolo amigable con los usuarios y atractivo para ellos.<br>Las audiencias se transforman con el paso del tiempo, y tu logo no debe quedarse atrás. El equipo de profesionales de Oddel, en conjunto con tus ideas, expectativas y lo que busques transmitir, se encargarán de estudiar tu target y todos aquellos factores de influencia para determinar cuál será el mejor diseño para tu logo.',
    button1:'Quiero mi logo',
    title2:'Merchandising',
    p2:'Haz que tu marca llame la atención en todo sentido. Promocionar y vender tus productos con Merchandising es una gran estrategia.<br>Estas acciones atraen a los clientes hacia tu marca y los hace más cercano a ellas, así se obtiene un mayor flujo de ventas. En Oddel, nos encargamos de desarrollar todos los elementos necesarios para que tu estrategia de Merchandising sea óptima y acapare la atención del mercado, saliendo de los márgenes convencionales y creando beneficios para tu marca.',
    button2:'Quiero tener Merchandising',
    title3:'Video animación y foto',
    p3:'Hay diversas formas de ser disruptivo en el mundo digital, y una de ellas, es hacerlo con acciones de comunicación de alto impacto con mensajes contundentes. Esto se puede transmitir con videos e imágenes.<br>Darle mayor vuelo a tu organización, comunicar sus valores, productos y formas de trabajo con elementos audiovisuales atraerán público, generará interacción y potenciará a tu marca.',
    button3:'Me interesa este servicio',
  },
  in:{
    title:'LinkedIn',
    sub:'LinkedIn facilita el networking con socios estratégicos, da información de la competencia y las ultimas novedades de tu sector. Conocé como puede crecer nu negocio',
    button:'Quiero crecer en LinkedIn',
    sabias: '¿Sabías que Linkedin cuenta con una base global de más de <b>774 millones</b> de usuarios?',
    alt1: 'Representación del mundo con iconos de personas de negocios',
    ademas: 'Además, <b>4 de cada 5</b> usuarios de LinkedIn cumplen <b>roles clave e influyentes</b> en la toma de decisión de miles de empresas',
    ademas_2: 'Por eso, LinkedIn es una de las redes más efectivas para hacer llegar tus productos y servicios a la gente correcta',
    sabemos: 'Sabemos de LinkedIn Marketing',
    sabemos_2: 'Siendo una de las únicas empresas en el mercado ofreciendo este servicio, Oddel puede ayudarte a llegar a profesionales relevantes dentro de esta magnífica red social, y de esta manera hacer crecer a tu negocio y red de contactos profesionales.',
    bullets:{
      t1:'Date a conocer',
      p1:'Llama la atención de personas influyentes en la toma de decisiones empresariales',
      t2:'Genra tráfico hacia tu sitio web',
      p2:'Haz que potenciales clientes lleguen a tu punto de información y muéstrales tus productos y servicios',
      t3:'Genera leads',
      p3:'Utiliza el remarketing y las conexiones a fin de comunicar tu contenido y atraer leads para tu negocio'
    },
    optimation:{
      title:'¿Cómo optimizamos tu perfil?',
      list_titles:['Creación de perfil','Video institucional', 'Tecto institucional','Banner institucional',
                  'Especialista part-time', 'Cración y publicación de contenido relevante',
                  'Presentación de contenido mensual', 'Identificación de potenciales clientes',
                  'Contacto con clientes y seguimiento', 'Manejo de intracciones y solicitudes'
                  ]
    }
  },
  contact:{
    title:'Contactanos',
    p1:'Podemos otorgarle a tu negocio todas las herramientas necesarias para posicionarse.',
    p2:'Nos gustaría ser parte de tu equipo y realizar una labor en conjunto, nuestra intención es ir más allá de los vínculos laborales e implementar una visión de “socio-amigo” interiorizándonos en tu empresa para brindar el mejor servicio.',
    p3:'Vamos a dedicarnos a tus preocupaciones y objetivos, trabajar arduamente y lograr resultados magníficos juntos    ',
    faqTitle:'Preguntas frecuentes',
    f1:'El Marketing Digital es la aplicación de estrategias de marketing o comercialización llevadas a cabo en plataformas digitales.',
    f2:'El Marketing Digital sirve para contactar al vendedor de un producto o servicio con sus potenciales clientes a través de plataformas digitales. Sus beneficios son: alcance global, precisión en la segmentación, resultados medibles e inmediatez.',
    f3:'Un proceso de conversión consiste en llevar a un usuario a nuestra web, creada para ofrecerle el contenido adecuado según su estado en el ciclo de compra.',
    f4:'La Puja es una subasta en la cual nuestra campaña va a participar con los demás anunciantes. Quienes paguen más serán aquellos que aparecerán primeros.',
    f5:'El Marketing Online no es lo mismo que el Marketing Digital, ya que el Marketing Online se basa solo en el uso del internet mientras que el Marketing digital abarca todos los medios digitales que existen.',
    f6:'Una cookie es una pieza de información almacenada en el navegador del usuario. Sirve para registrar la actividad del usuario sobre un sitio y rastrear, por ejemplo, la cantidad de veces que el usuario ha visitado el sitio web.',
    f7:'El Engagement es el “compromiso” que tienen los usuarios con una marca, a raíz de la capacidad de un producto para crear una relación sólida y perdurable en el tiempo con ellos. Estos no son todos los seguidores que tiene una marca, sino los que interactúan con ella.',
    f8:'El marketing de afiliación consiste en realizar una serie de acuerdos con otras webs para promocionar tu contenido a cambio de una comisión. Cada vez que alguien haga clic en el banner que tengas en otra web, la misma se llevará una comisión pactada previamente. Lo mismo ocurre al revés para quien quiera publicitarse en tu web. Si existe acuerdo, hay entonces afiliación.',
    f9:'El Remarketing es una técnica de marketing que consiste en mostrar tus anuncios a personas que han visto una página específica de tu sitio web.',
    f10:'Hoy en día el Marketing Tradicional cuenta con muchísimas limitaciones en cuanto a la segmentación del target, además de su gran dificultad para la medición del impacto y de su ROI, en cambio, el Marketing digital, centra su estrategia en la segmentación del público objetivo (edad, genero, intereses, ciudad, país, poder de compra, estado de ánimo, datos de interés, entre muchas otras más).',
    f1t:'¿Qué es el Marketing Digital?',
    f2t:'¿Para qué sirve el Marketing Digital?',
    f3t:'¿Qué son las conversiones en el marketing digital?',
    f4t:'¿Qué es una Puja?',
    f5t:'¿Es lo mismo Marketing Online que Marketing Digital?',
    f6t:'¿Qué es una cookie?',
    f7t:'¿Qué es el Engagement?',
    f8t:'¿Qué es el marketing de afiliación?',
    f9t:'¿Qué es el Remarketing?',
    f10t:'¿Cuál es la diferencia entre el Marketing Digital y el Marketing Tradicional?',
  },
  links:{
    home:'/es/index',
    in: '/es/linkedin',
    web:'/es/web',
    media:'/es/media-ads',
    com:'/es/comunicacion',
    contact:'/es/contacto',
    contact2:'../contacto',
  },
  form2:{
    l1:'Mi nombre es',
    l2:'Qiuiero información sobre:',
    l3:'Consultas / mensaje:',
    l4:'Mail de contacto',
    small:'Todos nuestros servicios incluyen asesoría gratuita',
    button:'Contactarme',
  },
  endForm:{title:'¿Listo para innovar tu negocio?', p:`Cuentanos sobre tu negocio y obtén asesoramiento gratuito`}
}
